// require("./javascript/jquery-3.2.1.min.js")
var $ = require("jquery")
require("./javascript/particles-min.js")
require("./javascript/particleconfig.js")
require("./javascript/typer.js")
require("./javascript/neon.js")
require("./javascript/neon2.js")
require("./slick/slick.js")
require("./jquery-ui/jquery-ui.min.js")
require("./javascript/jquery.js")
